### PR TITLE
Turn-Based Mode appcrash Fix (Hostile/Ally combat)

### LINKED ISSUE #9: Turn-Based Mode appcrash
Appcrash occurs whenever allied monster turned against hostiles within collision radius despite recent changes.

### PR DESCRIPTION
**Pull request by neutonm**
### Description:

**Appcrash occurs whenever allied monster turned against hostiles within collision radius**. 

_It's somehow caused by a RemoveMonsterLimitsAndPlaceMon.lua script pulled from MMerge. One of the addresses contained within mm7 code block was processed with wrong size.

### Issue

https://github.com/neutonm/might-and-magic-amber-island-mod/issues/9

### Changes: 

1. Moved 0x4bd223 address into SimpleReplacePtr call which utilized cmdSize 3
2. Game.MonsterTxt is now set to NewMonCount + 1 (last monster couldn't be accessed before, c-arrays)

### QA

Tested on Windows and Linux (wine).

- 30 min gameplay
- abused turn-based mode in dev-dungeon and near southern bridge at amber island town, forcing guards and lizards to fight with each other
- summoned warder mercenary to fight lizards and later on, inside Oak Hill cottage 
- added new monster to test monster limitation (MonsLists.txt +3). Works fine via SummonMonster call as well ass MAPSTATS.txt spawn.

### CODE REVIEW

File: Scripts/Structs/After/RemoveMonstersAndPlacemonLimits.lua [hunk 1]
```diff
@@ -174,7 +174,7 @@ if mmver > 6 then
 
 		end
 		mem.IgnoreProtection(false)
-		ChangeGameArray("MonstersTxt", NewStartPos, NewMonCount)
+		ChangeGameArray("MonstersTxt", NewStartPos, NewMonCount + 1)
```
Comment (Alkapivo) [inline Scripts/Structs/After/RemoveMonstersAndPlacemonLimits.lua]: `if mmver == 7 then` (line 41) section calls SimpleReplacePtr 4 times within those 40 lines of code. Maybe it's a good idea to write a comment here with some short explanation why those addresses, why +1 etc.

**Review by Alkapivo — CHANGES_REQUESTED** [review]

**Review by Alkapivo — APPROVED** [review]
